<?php
/**
 * Copyright © Wubinworks. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

use Wubinworks\DisableChangeEmail\Helper\System as SystemHelper;
?>
<?php if ($this->helper(SystemHelper::class)->isChangeEmailDisabled()): ?>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/lib/view/utils/dom-observer'
        ], function ($, $do) {
            $do.get('#change-email', function(elem){
                $(elem).prop('disabled', true);
                $(elem).prop('checked', false);
            });
        });
    </script>
<?php endif; ?>
